/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/Scene_2_Skills_MESH_v2.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

import * as THREE from 'three'

export function SkillsScene(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('models/Scene_2_Skills_MESH_v2.glb')

  // Assign texture
  const texture = useTexture('textures/SkillsSceneLayout_v3_CyclesBake_DIFFUSE.png')
  texture.flipY = false;
  texture.encoding = THREE.sRGBEncoding;

  // Set texture
  const textureMaterial = new THREE.MeshStandardMaterial({
    map: texture,
  })

  const texturGlassMaterial = new THREE.MeshPhysicalMaterial({
    roughness: 0,
    metalness: 0,
    transmission: 1,
  })
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.WallAccentLine001.geometry} material={materials['GB Matte Bluw Wall.002']} position={[-0.163, 5.661, -12.544]} rotation={[Math.PI / 2, 0, 0]} scale={[0.02, 0.109, 0.013]} >
        <meshStandardMaterial color={0x1b3579} metalness={0.5} roughness={0.2} />
      </mesh>
      <mesh geometry={nodes.RightWall001.geometry} material={materials['Matte Metallic Paint.002']} position={[-1.278, 4.2, -12.581]} scale={[5.44, 4.278, 0.03]} >
        <meshStandardMaterial color={0x000000} metalness={0.2} roughness={0.9} />
      </mesh>
      <mesh geometry={nodes.WindowFrame001.geometry} material={materials['GB Matte Bluw Wall.002']} position={[0.047, 0.125, -8.42]} scale={[0.826, 0.836, 0.826]} >
        <meshStandardMaterial color={0x1b3579} metalness={0.5} roughness={0.2} />
      </mesh>
      <mesh geometry={nodes.TopLevelRailing001.geometry} material={materials['Car chrome.002']} position={[0.047, 0.125, -8.42]} scale={[0.826, 0.836, 0.826]} >
        <meshStandardMaterial color={0xa8a9ad} metalness={1} roughness={0} />
      </mesh>
      <mesh geometry={nodes.GBSign001.geometry} material={materials['White Marble Texture.001']} position={[-1.172, 0.125, -8.42]} scale={[0.954, 0.967, 0.826]} >
        <meshStandardMaterial color={0xFFFFFF} metalness={0.5} roughness={0.2} />
      </mesh>
      <mesh geometry={nodes.LabEntrance001.geometry} material={materials['GB Matte Bluw Wall']} position={[-0.597, 0.125, -8.42]} scale={[0.954, 0.967, 0.826]} >
        <meshStandardMaterial color={0x1b3579} metalness={0.5} roughness={0.2} />
      </mesh>
      <mesh geometry={nodes.BookShelf001.geometry} material={materials['GB Matte Bluw Wall']} position={[0.047, 0.125, -8.42]} scale={[0.826, 0.836, 0.826]} >
        <meshStandardMaterial color={0x1b3579} metalness={0.5} roughness={0.2} />
      </mesh>
      <group position={[0.047, 0.125, -8.42]} scale={[0.826, 0.836, 0.826]}>
        <mesh geometry={nodes.Mesh_517001.geometry} material={texturGlassMaterial} />
        <mesh geometry={nodes.Mesh_517001_1.geometry} material={texturGlassMaterial}/>
      </group>
      <group position={[0.047, 0.125, -8.42]} scale={[0.826, 0.836, 0.826]}>
        <mesh geometry={nodes.Stairs.geometry} material={materials['wallSG.003']} >
        <meshStandardMaterial map={texture} metalness={0.5} roughness={0.2} />
      </mesh>
        <mesh geometry={nodes.Stairs_1.geometry} material={nodes.Stairs_1.material} >
        <meshStandardMaterial map={texture} metalness={0.5} roughness={0.2} />
      </mesh>
      </group>
      <mesh geometry={nodes.TopSkillsFloor_combined001.geometry} material={nodes.TopSkillsFloor_combined001.material} >
        <meshStandardMaterial map={texture} metalness={0.5} roughness={0.2} />
      </mesh>
      <mesh geometry={nodes.TopSkillsFloor_baked_Baked.geometry} material={materials.SkillsSceneLayout_Baked} >
        <meshStandardMaterial map={texture} metalness={0.5} roughness={0.2} />
      </mesh>
      <mesh geometry={nodes.BackWallBottom_baked_Baked.geometry} material={materials.SkillsSceneLayout_Baked} >
        <meshStandardMaterial map={texture} metalness={0.5} roughness={0.2} />
      </mesh>
      <mesh geometry={nodes.SkillsFloorPlug1_baked_Baked.geometry} material={materials.SkillsSceneLayout_Baked} >
        <meshStandardMaterial map={texture} metalness={0.5} roughness={0.2} />
      </mesh>
      <mesh geometry={nodes.SkillsFloorPlug2_baked_Baked.geometry} material={materials.SkillsSceneLayout_Baked} >
        <meshStandardMaterial map={texture} metalness={0.5} roughness={0.2} />
      </mesh>
      <mesh geometry={nodes.SkillsFloor_baked_Baked.geometry} material={materials.SkillsSceneLayout_Baked} >
        <meshStandardMaterial map={texture} metalness={0.5} roughness={0.2} />
      </mesh>
      <mesh geometry={nodes.StairsSteps_baked_Baked.geometry} material={materials.SkillsSceneLayout_Baked} >
        <meshStandardMaterial map={texture} metalness={0.5} roughness={0.2} />
      </mesh>
      <mesh geometry={nodes.TopBackWall_baked_Baked.geometry} material={materials.SkillsSceneLayout_Baked} >
        <meshStandardMaterial map={texture} metalness={0.5} roughness={0.2} />
      </mesh>
    </group>
  )
}

useGLTF.preload('models/Scene_2_Skills_MESH_v2.glb')
